# Generated by Django 6.0.6 on 2026-07-11 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('number_pool', '0005_alter_numberpool_options_numberpool_assigned_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberpool',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='numbers', to='number_pool.country'),
        ),
    ]
