# Generated by Django 6.0.6 on 2026-07-15 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carriers', '0003_termination'),
        ('number_pool', '0006_alter_numberpool_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='numberpool',
            name='provider',
        ),
        migrations.AddField(
            model_name='numberpool',
            name='carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='numbers', to='carriers.carrier'),
        ),
        migrations.AddField(
            model_name='numberpool',
            name='termination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='numbers', to='carriers.termination'),
        ),
    ]
