# Generated by Django 6.0.6 on 2026-08-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('number_pool', '0007_remove_numberpool_provider_numberpool_carrier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='numberpool',
            name='currency',
            field=models.CharField(blank=True, db_column='Currency', default='', max_length=10),
        ),
        migrations.AddField(
            model_name='numberpool',
            name='daily',
            field=models.DecimalField(db_column='Daily', decimal_places=6, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='numberpool',
            name='monthly30',
            field=models.DecimalField(db_column='Monthly30', decimal_places=6, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='numberpool',
            name='monthly45',
            field=models.DecimalField(db_column='Monthly45', decimal_places=6, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='numberpool',
            name='monthly60',
            field=models.DecimalField(db_column='Monthly60', decimal_places=6, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='numberpool',
            name='number',
            field=models.CharField(blank=True, db_column='Number', max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='numberpool',
            name='payout',
            field=models.DecimalField(db_column='Payout', decimal_places=6, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='numberpool',
            name='payterm',
            field=models.IntegerField(db_column='Payterm', default=30),
        ),
        migrations.AddField(
            model_name='numberpool',
            name='prefix',
            field=models.CharField(blank=True, db_column='Prefix', default='', max_length=30),
        ),
        migrations.AddField(
            model_name='numberpool',
            name='qty',
            field=models.DecimalField(blank=True, db_column='Qty', decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='numberpool',
            name='range_name',
            field=models.CharField(blank=True, db_column='Range_Name', default='', max_length=255),
        ),
        migrations.AddField(
            model_name='numberpool',
            name='weekly',
            field=models.DecimalField(db_column='Weekly', decimal_places=6, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='numberpool',
            name='weekly7',
            field=models.DecimalField(db_column='Weekly7', decimal_places=6, default=0, max_digits=15),
        ),
    ]
