# Generated by Django 6.0.6 on 2026-08-16 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('number_pool', '0008_numberpool_currency_numberpool_daily_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='numberpool',
            name='extension',
        ),
    ]
