# Generated by Django 6.0.6 on 2026-08-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('number_pool', '0009_remove_numberpool_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='numberpool',
            name='daily_max_call',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='numberpool',
            name='daily_max_duration',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='numberpool',
            name='is_test_number',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='numberpool',
            name='number_mode',
            field=models.CharField(choices=[('SINGLE', 'Single Number'), ('RANGE', 'Range'), ('LIST', 'List'), ('CSV', 'CSV Upload')], default='SINGLE', max_length=20),
        ),
        migrations.AddField(
            model_name='numberpool',
            name='number_service',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='numberpool',
            name='number_type',
            field=models.CharField(choices=[('TEST', 'Test Number'), ('GENERAL', 'General')], default='GENERAL', max_length=20),
        ),
        migrations.AddField(
            model_name='numberpool',
            name='service_variables',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='numberpool',
            name='total_numbers',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
