# Generated by Django 6.0.6 on 2026-09-02 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('number_pool', '0010_numberpool_daily_max_call_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='numberpool',
            options={'ordering': ['did_number']},
        ),
        migrations.RemoveField(
            model_name='numberpool',
            name='country',
        ),
    ]
