# Generated by Django 6.0.6 on 2026-07-05 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_alter_client_created_by'),
        ('companies', '0002_alter_company_created_by'),
        ('number_pool', '0002_numberpool_is_active_alter_numberpool_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SIPAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('auth_id', models.CharField(max_length=50, unique=True)),
                ('domain', models.CharField(default='pbx.local', max_length=255)),
                ('transport', models.CharField(choices=[('UDP', 'UDP'), ('TCP', 'TCP'), ('TLS', 'TLS')], default='UDP', max_length=10)),
                ('context', models.CharField(default='from-internal', max_length=100)),
                ('caller_id', models.CharField(blank=True, max_length=100)),
                ('codecs', models.CharField(default='ulaw,alaw', max_length=255)),
                ('nat', models.BooleanField(default=True)),
                ('qualify', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sip_accounts', to='clients.client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sip_accounts', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sip_account', to='number_pool.numberpool')),
            ],
            options={
                'db_table': 'sip_accounts',
                'ordering': ['username'],
            },
        ),
    ]
