# Generated by Django 6.0.6 on 2026-07-10 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sip', '0002_alter_sipaccount_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sipaccount',
            name='company',
        ),
        migrations.AddField(
            model_name='sipaccount',
            name='admin',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'COMPANY_ADMIN'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sip_accounts', to=settings.AUTH_USER_MODEL),
        ),
    ]
