# Generated by Django 6.0.6 on 2026-07-12 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('number_pool', '0006_alter_numberpool_country'),
        ('sip', '0003_remove_sipaccount_company_sipaccount_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sipaccount',
            name='number',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sip_account', to='number_pool.numberpool'),
        ),
    ]
