# Generated by Django 6.0.6 on 2026-07-12 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('number_pool', '0006_alter_numberpool_country'),
        ('sip', '0004_alter_sipaccount_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sipaccount',
            name='codecs',
            field=models.CharField(default='ulaw,alaw', editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='sipaccount',
            name='context',
            field=models.CharField(default='from-internal', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='sipaccount',
            name='domain',
            field=models.CharField(default='pbx.local', editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='sipaccount',
            name='nat',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='sipaccount',
            name='number',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sip_account', to='number_pool.numberpool'),
        ),
        migrations.AlterField(
            model_name='sipaccount',
            name='qualify',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
