# Generated by Django 6.0.6 on 2026-07-16 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_alter_company_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('destination_type', models.CharField(choices=[('extension', 'Extension'), ('ivr', 'IVR'), ('queue', 'Queue'), ('ringgroup', 'Ring Group')], max_length=20)),
                ('destination', models.CharField(max_length=100)),
                ('priority', models.IntegerField(default=1)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_routes', to='companies.company')),
            ],
        ),
    ]
