# Generated by Django 6.0.6 on 2026-08-12 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carriers', '0003_termination'),
        ('inbound', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inboundroute',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='inboundroute',
            name='destination_type',
        ),
        migrations.AddField(
            model_name='inboundroute',
            name='forward_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='inboundroute',
            name='termination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inbound_routes', to='carriers.termination'),
        ),
    ]
