# Generated by Django 6.0.6 on 2026-08-13 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_company_created_by'),
        ('inbound', '0002_remove_inboundroute_destination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboundroute',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_routes', to='companies.company'),
        ),
    ]
