# Generated by Django 6.0.6 on 2026-08-15 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0003_alter_inboundroute_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inboundroute',
            name='company',
        ),
    ]
