# Generated by Django 6.0.6 on 2026-07-11 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uniqueid', models.CharField(max_length=100, unique=True)),
                ('linkedid', models.CharField(blank=True, max_length=100)),
                ('caller', models.CharField(max_length=50)),
                ('receiver', models.CharField(max_length=50)),
                ('caller_channel', models.CharField(max_length=200)),
                ('receiver_channel', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('RINGING', 'Ringing'), ('ANSWERED', 'Answered'), ('HANGUP', 'Hangup')], default='RINGING', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', related_query_name='%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'live_calls',
                'ordering': ['-started_at'],
            },
        ),
    ]
