# Generated by Django 6.0.6 on 2026-07-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ami', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livecall',
            name='status',
            field=models.CharField(choices=[('RINGING', 'Ringing'), ('DIALING', 'Dialing'), ('ANSWERED', 'Answered'), ('HANGUP', 'Hangup')], default='RINGING', max_length=20),
        ),
    ]
