# Generated by Django 6.0.6 on 2026-09-14 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ami', '0003_extensionstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='livecall',
            name='cause',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
