from apps.sip.models import SIPAccount


class PJSIPGenerator:

    @staticmethod
    def generate(account):

        caller_id = (
            account.caller_id
            or (
                account.number.did_number
                if account.number
                else account.username
            )
        )

        return f"""
; ==================================================
; Auto Generated by VoIP Backend
; Extension : {account.username}
; ==================================================

[{account.username}]
type=endpoint
transport=transport-{account.transport.lower()}
context={account.context}

disallow=all
allow={account.codecs}

auth={account.auth_id}
aors={account.username}

callerid="{account.client.name}" <{caller_id}>

direct_media=no
rewrite_contact=yes
force_rport=yes
rtp_symmetric=yes

dtmf_mode=rfc4733
language=en

[{account.auth_id}]
type=auth
auth_type=userpass

username={account.username}
password={account.password}

[{account.username}]
type=aor

max_contacts=1
remove_existing=yes
qualify_frequency=60

"""

    @staticmethod
    def generate_all():

        config = """
; ==================================================
; AUTO GENERATED PJSIP FILE
; DO NOT EDIT MANUALLY
; ==================================================

"""

        accounts = (
            SIPAccount.objects
            .filter(status="ACTIVE")
            .select_related(
                "client",
                "number",
            )
        )

        for account in accounts:

            config += (
                PJSIPGenerator.generate(
                    account
                )
            )

        return config