from apps.sip.models import SIPAccount
from apps.carriers.models import Carrier


class PJSIPGenerator:

    # ======================================================
    # SIP ACCOUNT
    # ======================================================

    @staticmethod
    def generate(account):

        return f"""
; ==================================================
; Auto Generated by VoIP Backend
; Extension : {account.username}
; ==================================================

[{account.username}]
type=endpoint
transport=transport-{account.transport.lower()}
context={account.context}

disallow=all
allow={account.codecs}

auth={account.auth_id}
aors={account.username}

callerid="{account.client.name}" <{account.number.extension}>

direct_media=no
rewrite_contact=yes
force_rport=yes
rtp_symmetric=yes

dtmf_mode=rfc4733
language=en

[{account.auth_id}]
type=auth
auth_type=userpass

username={account.username}
password={account.password}

[{account.username}]
type=aor

max_contacts=1
remove_existing=yes
qualify_frequency=60

"""

    # ======================================================
    # CARRIER
    # ======================================================

    @staticmethod
    def generate_carrier(carrier):

        config = f"""
; ==================================================
; Carrier : {carrier.name}
; ==================================================

[{carrier.name}]
type=endpoint
transport=transport-udp
context=from-carrier

disallow=all
allow=all

direct_media=no
rewrite_contact=yes
force_rport=yes
rtp_symmetric=yes

"""

        ips = carrier.ips.filter(is_active=True)

        for index, ip in enumerate(ips, start=1):

            config += f"""
[{carrier.name}-identify-{index}]
type=identify
endpoint={carrier.name}
match={ip.ip_address}

"""

        return config

    # ======================================================
    # GENERATE COMPLETE CONFIG
    # ======================================================

    @staticmethod
    def generate_all():

        config = ""

        config += """
; ==================================================
; AUTO GENERATED FILE
; DO NOT EDIT MANUALLY
; ==================================================

"""

        # -----------------------------
        # SIP Accounts
        # -----------------------------

        accounts = (
            SIPAccount.objects.filter(status="ACTIVE")
            .select_related(
                "client",
                "number",
            )
        )

        for account in accounts:
            config += PJSIPGenerator.generate(account)

        # -----------------------------
        # Carriers
        # -----------------------------

        carriers = (
            Carrier.objects.filter(is_active=True)
            .prefetch_related("ips")
        )

        for carrier in carriers:
            config += PJSIPGenerator.generate_carrier(carrier)

        return config