# Generated by Django 6.0.6 on 2026-07-12 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('number_pool', '0006_alter_numberpool_country'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.CharField(max_length=150)),
                ('prefix', models.CharField(db_index=True, max_length=20)),
                ('provider', models.CharField(blank=True, max_length=100)),
                ('buy_rate', models.DecimalField(decimal_places=6, max_digits=10)),
                ('sell_rate', models.DecimalField(decimal_places=6, max_digits=10)),
                ('billing_block', models.PositiveIntegerField(choices=[(1, '1/1'), (6, '6/6'), (30, '30/30'), (60, '60/60')], default=60)),
                ('minimum_duration', models.PositiveIntegerField(default=60)),
                ('connection_charge', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('effective_date', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='number_pool.country')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', related_query_name='%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'billing_rates',
                'ordering': ['country__name', 'destination'],
                'indexes': [models.Index(fields=['prefix'], name='billing_rat_prefix_2295a6_idx'), models.Index(fields=['status'], name='billing_rat_status_42c3bf_idx'), models.Index(fields=['effective_date'], name='billing_rat_effecti_15b785_idx')],
                'constraints': [models.UniqueConstraint(fields=('prefix', 'provider', 'effective_date'), name='unique_rate_version')],
            },
        ),
    ]
