# Generated by Django 6.0.6 on 2026-07-11 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caller', models.CharField(max_length=50)),
                ('callee', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('uniqueid', models.CharField(max_length=100, unique=True)),
                ('channel', models.CharField(blank=True, max_length=150)),
                ('disposition', models.CharField(choices=[('ANSWERED', 'Answered'), ('NO ANSWER', 'No Answer'), ('BUSY', 'Busy'), ('FAILED', 'Failed'), ('CANCEL', 'Cancel')], default='ANSWERED', max_length=30)),
                ('start_time', models.DateTimeField()),
                ('answer_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField()),
                ('duration', models.PositiveIntegerField(default=0)),
                ('billsec', models.PositiveIntegerField(default=0)),
                ('recording', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
    ]
