# Generated by Django 6.0.6 on 2026-07-11 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdr', '0001_initial'),
        ('sip', '0003_remove_sipaccount_company_sipaccount_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callrecord',
            name='callee',
        ),
        migrations.RemoveField(
            model_name='callrecord',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='callrecord',
            name='recording',
        ),
        migrations.RemoveField(
            model_name='callrecord',
            name='source',
        ),
        migrations.AddField(
            model_name='callrecord',
            name='application',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='callrecord',
            name='caller_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='callrecord',
            name='caller_number',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='callrecord',
            name='context',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='callrecord',
            name='destination_channel',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='callrecord',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_calls', to='sip.sipaccount'),
        ),
        migrations.AddField(
            model_name='callrecord',
            name='receiver_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='callrecord',
            name='receiver_number',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='callrecord',
            name='caller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_calls', to='sip.sipaccount'),
        ),
        migrations.AlterField(
            model_name='callrecord',
            name='channel',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='callrecord',
            name='uniqueid',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AlterModelTable(
            name='callrecord',
            table='call_records',
        ),
    ]
