# Generated by Django 6.0.6 on 2026-07-12 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdr', '0002_remove_callrecord_callee_and_more'),
        ('number_pool', '0006_alter_numberpool_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrecord',
            name='amount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='callrecord',
            name='billable_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='callrecord',
            name='billing_block',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='callrecord',
            name='buy_rate',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='callrecord',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cdrs', to='number_pool.country'),
        ),
        migrations.AddField(
            model_name='callrecord',
            name='destination',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='callrecord',
            name='invoice_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('INVOICED', 'Invoiced')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='callrecord',
            name='prefix',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='callrecord',
            name='provider',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='callrecord',
            name='sell_rate',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
    ]
