# Generated by Django 6.0.6 on 2026-08-19 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdr', '0003_callrecord_amount_callrecord_billable_seconds_and_more'),
        ('number_pool', '0009_remove_numberpool_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrecord',
            name='number_pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cdrs', to='number_pool.numberpool'),
        ),
    ]
