# Generated by Django 6.0.6 on 2026-09-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdr', '0004_callrecord_number_pool'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrecord',
            name='cause',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='callrecord',
            name='disposition',
            field=models.CharField(default='UNKNOWN', max_length=100),
        ),
    ]
