# Generated by Django 6.0.6 on 2026-07-15 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carriers', '0003_termination'),
        ('routing_plans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prefix', models.CharField(max_length=30)),
                ('strip_digits', models.PositiveIntegerField(default=0)),
                ('add_prefix', models.CharField(blank=True, default='', max_length=30)),
                ('priority', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', related_query_name='%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('routing_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='routing_plans.routingplan')),
                ('termination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='carriers.termination')),
            ],
            options={
                'verbose_name': 'Route',
                'verbose_name_plural': 'Routes',
                'db_table': 'routes',
                'ordering': ['routing_plan', 'priority', 'prefix'],
                'constraints': [models.UniqueConstraint(fields=('routing_plan', 'termination', 'prefix', 'priority'), name='unique_route_priority')],
            },
        ),
    ]
