# Generated by Django 6.0.6 on 2026-07-15 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carriers', '0002_alter_carrier_options_alter_carrierip_options_and_more'),
        ('routing_plans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prefix', models.CharField(max_length=30)),
                ('strip_digits', models.PositiveIntegerField(default=0)),
                ('add_prefix', models.CharField(blank=True, default='', max_length=30)),
                ('priority', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True, default='')),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='carriers.carrier')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', related_query_name='%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('routing_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='routing_plans.routingplan')),
            ],
            options={
                'db_table': 'routes',
                'ordering': ['routing_plan', 'priority', 'prefix'],
                'unique_together': {('routing_plan', 'carrier', 'prefix', 'priority')},
            },
        ),
    ]
