# Generated by Django 6.0.6 on 2026-07-15 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carriers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrier',
            options={'ordering': ['name'], 'verbose_name': 'Carrier', 'verbose_name_plural': 'Carriers'},
        ),
        migrations.AlterModelOptions(
            name='carrierip',
            options={'ordering': ['carrier', 'ip_address'], 'verbose_name': 'Carrier IP', 'verbose_name_plural': 'Carrier IPs'},
        ),
        migrations.AlterUniqueTogether(
            name='carrierip',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='carrier',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', related_query_name='%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carrierip',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', related_query_name='%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carrierip',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name='carrierip',
            constraint=models.UniqueConstraint(fields=('carrier', 'ip_address'), name='unique_carrier_ip'),
        ),
    ]
