# Generated by Django 6.0.6 on 2026-07-15 12:50

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carriers', '0002_alter_carrier_options_alter_carrierip_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Termination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('prefix', models.CharField(max_length=20)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('payment_term', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Weekly7', 'Weekly7'), ('Monthly30', 'Monthly30'), ('Monthly45', 'Monthly45'), ('Monthly60', 'Monthly60')], default='Monthly30', max_length=20)),
                ('carrier_payout', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10)),
                ('daily_payout', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10)),
                ('weekly_payout', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10)),
                ('weekly7_payout', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10)),
                ('monthly30_payout', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10)),
                ('monthly45_payout', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10)),
                ('monthly60_payout', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10)),
                ('max_duration', models.PositiveIntegerField(default=0)),
                ('info', models.TextField(blank=True, null=True)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminations', to='carriers.carrier')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', related_query_name='%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Termination',
                'verbose_name_plural': 'Terminations',
                'db_table': 'terminations',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('carrier', 'name'), name='unique_carrier_termination')],
            },
        ),
    ]
