# Generated by Django 6.0.6 on 2026-07-10 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asterisk', '0002_alter_provisionjob_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='provisionjob',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], default='CREATE', max_length=20),
        ),
        migrations.AddField(
            model_name='provisionjob',
            name='error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='provisionjob',
            name='retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='provisionjob',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
    ]
